name: medill
description: A minimalistic, easy backend framework for Dart.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.0 <3.0.0'


dependencies:
  sqlite3: ^1.6.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
